### ISSUE TITLE
ĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄĄ

### ISSUE THREAD

**Issue by BruhBruva** [piotr-pacula/analiza_geoinformacyjna_projekt#1]
![image](https://github.com/piotr-pacula/analiza_geoinformacyjna_projekt/assets/162442264/d1b9f666-31c3-40e0-9bbb-4790bce5d24a)

**Comment by BruhBruva** [comment]
- [ ] struggle with qgis

- [ ] crush your enemies with a wall

- [ ] make a flip

**Comment by piotr-pacula** [comment]
Ę
